run:
  allow-parallel-runners: false
linters:
  disable:
    - forbidigo
    - gofumpt
    - ifshort
    - importas
    - tparallel
    - wsl
    - depguard
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  fast: false

linters-settings:
  goimports:
    local-prefixes: cash2ynab/
  gci:
    sections:
      - standard
      - default
      - prefix(cash2ynab)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - exhaustruct
        - funlen
        - goconst
