# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: |
            go.sum
            go.sum

      - name: Install CI dependencies
        run: make install-ci-dependencies

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Security check
        run: make security-check

      - name: Test
        run: make test-coverage
